title: "Benjamin Lu"
tagline: "WordPress Developer"

primary:
  - title: "About Me"
    url:   "/about-me"
  - title: "Archives"
    url:   "/archives"
  - title: "Contact Me"
    url:   "/contact-me"

social:
  - title: "Facebook"
    url: "https://www.facebook.com/benlumia007"
  - title: "Twitter"
    url: "https://twitter.com/benlumia007"
  - title: "WordPress"
    url: "https://profiles.wordpress.org/benlumia007/"