name: benjlu

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: step one
        uses: actions/checkout@v2
      - name: step two
        run: composer install
      - name: step three
        run: npm install
      - name: step four
        run: npm run build
      - name: step five
        run: sed -i -e "s/benjlu.test/benjlu.com/g" "app/functions-config.php"
      - name: step six
        run: rsync -r benjlu/* ~/public_html