name: benjlu

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: step one
        uses: actions/checkout@v2
      - name: step two
        run: npm install
      - name: step three
        run: composer install